#!/usr/bin/env python
from sys import stdout, argv
from digilog_n.Layer.NotificationLayer import NotificationLayer
from digilog_n.Layer.AnalysisLayer import AnalysisLayer
from digilog_n.Layer.ArchiveLayer import ArchiveLayer
from digilog_n.Layer.IdentityLayer import IdentityLayer
from digilog_n.Layer.IMSLayer import IMSLayer
from digilog_n.Layer.DecisionMakerLayer import DecisionMakerLayer
import logging


mylogger = logging.getLogger("mylogger")
formatter = logging.Formatter('[%(levelname)s] %(message)s')
handler = logging.StreamHandler(stream=stdout)
handler.setFormatter(formatter)
handler.setLevel(logging.INFO)
mylogger.addHandler(handler)
mylogger.setLevel(logging.INFO)

mylogger.critical("System Logger: Showing CRITICAL Messages")
mylogger.error("System Logger: Showing ERROR Messages")
mylogger.warning("System Logger: Showing WARNING Messages")
mylogger.info("System Logger: Showing INFO Messages")
mylogger.debug("System Logger: Showing DEBUG Messages")


if __name__ == '__main__':
    processes = []

    processes.append(NotificationLayer())
    processes.append(DecisionMakerLayer())
    processes.append(AnalysisLayer())
    processes.append(ArchiveLayer())
    processes.append(IMSLayer())
    processes.append(IdentityLayer())

    for p in processes:
        p.start()

    for p in processes:
        p.join()



