#!/usr/bin/env python
##############################################################################
# for_rt_graph
# https://github.com/DigiLog-N/DigiLog-N
# Copyright 2020 Canvass Labs, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
from digilog_n.PlasmaReader import PlasmaReader
from time import sleep
import pandas as pd
import socket


pd.set_option('display.max_columns', None)
pd.set_option('max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_rows', None)


pr = PlasmaReader('/tmp/plasma', 'RUL_RSLT')

current_unit = 0
unit_count = 1

while True:
    df = pr.to_pandas()
    if df is not None:
        df['colFromIndex'] = df.index
        df = df.sort_values(by=['unit_id', 'colFromIndex'])
        for i in range(0, len(df)):
            unit_id = df.iloc[i]['unit_id']
            rul_prediction = df.iloc[i]['rul_predict']

            if unit_id > current_unit:
                current_unit = unit_id
                unit_count = 1
            else:
                unit_count += 1

            msg = "%d\t%s\t%f" % (unit_id, unit_count, rul_prediction)
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.sendto(msg.encode('utf-8'), ('127.0.0.1', 9090))
            print(msg)
            sleep(0.1)

