#!/usr/bin/env python
##############################################################################
# reset_demo
# https://github.com/DigiLog-N/DigiLog-N
# Copyright 2020 Canvass Labs, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
from digilog_n.PlasmaReader import PlasmaReader

pr = PlasmaReader('/tmp/plasma', 'RUL_RSLT', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma', 'NOTIFY', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma', 'ANNO_PRTS', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma', 'ANNO_GRPS', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma_full', 'RUL_RSLT', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma_full', 'NOTIFY', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma_full', 'ANNO_PRTS', remove_after_reading=True)
df = pr.to_pandas()

pr = PlasmaReader('/tmp/plasma_full', 'ANNO_GRPS', remove_after_reading=True)
df = pr.to_pandas()
