#!/usr/bin/env python
##############################################################################
# tap_phm08
# https://github.com/DigiLog-N/DigiLog-N
# Copyright 2020 Canvass Labs, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################
from digilog_n.PlasmaReader import PlasmaReader
from time import sleep
import pandas as pd


pd.set_option('display.max_columns', None)
pd.set_option('max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_rows', None)


pr = PlasmaReader('/tmp/plasma', 'PHM08')

while True:
    df = pr.to_pandas()
    if df is not None:
        print(df.info())
        print(df.head())
    sleep(1)
